version: '3.1'
services:

  db:
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=jamfsoftware
      - MYSQL_PASSWORD=jamfsw03
      - MYSQL_DATABASE=jamfsoftware
    networks:
      - jss
      - default

  memcached:
    image: memcached
    networks:
      - jss

  jss:
    build:
      context: ..
      dockerfile: Dockerfile.tomcat85.jre8.noconfd
    volumes:
      - "./jamf_cloud:/usr/local/tomcat/webapps/ROOT/WEB-INF/jamf_cloud:ro"
      - "./SystemProperties.xml:/usr/local/tomcat/webapps/ROOT/WEB-INF/xml/SystemProperties.xml:ro"
    ports:
      - "8444:8443"
      - "9080:8080"
      - "10001:10001" # JMX
      - "10002:10002"
    depends_on:
      - db
      - memcached
    environment:
      - JSS_DB_HOST=clouddb
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03

volumes:
  db-data:
    driver: local

networks:
  jss:
