version: '3.1'

services:  

  db:
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=jamfsoftware
      - MYSQL_PASSWORD=jamfsw03
      - MYSQL_DATABASE=jamfsoftware
    networks:
      - jss
      - default

  memcached:
    image: memcached
    networks:
      - jss

  jss:
    build:
      context: .
      dockerfile: Dockerfile.tomcat85.jre8.noconfd
    ports:
      - "8444:8443"
      - "9080:8080"
    depends_on:
      - db
      - memcached
    environment:
      - JSS_DB_HOST=db
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03
#      - PKCS12_PASS=changeit
#      - PKCS12_SRCALIAS=localhost
#      - SELF_SIGNED=0
#    volumes:
#      - "./server.p12:/server.p12:ro"
    networks:
      - jss
      - default

#  samba:
#    image: dperson/samba:latest
#    ports:
#      - "7139:139"
#      - "7445:445"
#    volumes:
#      - "./distribution_point:/distribution_point"
#    command:
#      - "-u"
#      - "jss;jss"
#      - "-s"
#      - "distribution_point;/distribution_point;yes;no;yes;all;jss"
#      - "-p"
#    environment:
#      - TZ=UTC


volumes:
  db-data:
    driver: local

networks:
  jss:
