version: '2'
services:  
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=jamfsoftware
      - MYSQL_PASSWORD=jamfsw03
      - MYSQL_DATABASE=jamfsoftware

  memcached:
    image: memcached
    networks:
      - jss

  jss:
    build:
      context: .
      dockerfile: Dockerfile.tomcat80.jre8.noconfd
    ports:
      - "8444:8443"
      - "9080:8080"
      - "9000:9000"
      - "9001:9001"
    links:
      - mysql:db
    depends_on:
      - mysql
    environment:
      - JSS_DB_HOST=db
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03
    networks:
      - jss
      - default

  samba:
    image: dperson/samba:latest
    ports:
      - "7139:139"
      - "7445:445"
    volumes:
      - "./distribution_point:/distribution_point"
    command:
      - "-u"
      - "jss;jss"
      - "-s"
      - "distribution_point;/distribution_point;yes;no;yes;all;jss"
      - "-p"
    environment:
      - TZ=UTC


volumes:
  db-data:
    driver: local

networks:
  jss: